[package]
name = "dnsmon-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
ctrlc = "3.4.4"
libbpf-rs = "0.24"
once_cell = "1.19.0"
pnet = "0.34.0"
regex = "1.10.4"

[build-dependencies]
libbpf-cargo = "0.24"
